ALTER TABLE sessions ADD COLUMN context_json TEXT;

INSERT OR REPLACE INTO exercises (id, name, category, muscle_groups, equipment, form_cues, form_video_url, created_at) VALUES
('ex-band-row', 'Band Row', 'strength', 'back,biceps,rear_delts', 'band', 'Anchor the band under the feet or around a fixed post. Pull elbows back, pause, and keep ribs down.', 'https://www.youtube.com/watch?v=gm2_6DX_0Bw', strftime('%s','now')),
('ex-band-good-morning', 'Band Good Morning', 'strength', 'hamstrings,glutes,lower_back', 'band', 'Stand on the band with it behind the neck or shoulders. Push hips back, keep spine long, then squeeze glutes to stand.', 'https://www.youtube.com/watch?v=CTRaCzE8pWU', strftime('%s','now')),
('ex-band-chest-press', 'Band Chest Press', 'strength', 'chest,shoulders,triceps', 'band', 'Press the band forward from chest height. Keep shoulders down and ribs stacked.', 'https://www.youtube.com/watch?v=2XDzSxSddXU', strftime('%s','now')),
('ex-band-curl', 'Band Curl', 'strength', 'biceps,forearms', 'band', 'Stand on the band, pin elbows near the ribs, curl without swinging.', 'https://www.youtube.com/watch?v=3Jqd9n2Poek', strftime('%s','now')),
('ex-db-bench-press', 'DB Bench Press', 'strength', 'chest,shoulders,triceps', 'dumbbell,bench', 'Set shoulder blades on the bench. Lower dumbbells under control, press without letting shoulders roll forward.', 'https://www.youtube.com/watch?v=VmB1G1K7v94', strftime('%s','now')),
('ex-goblet-squat', 'Goblet Squat', 'strength', 'quads,glutes,core', 'dumbbell,kettlebell', 'Hold the weight high against the chest. Sit between the hips, keep torso tall, and drive through the floor.', 'https://www.youtube.com/watch?v=MeIiIdhvXT4', strftime('%s','now')),
('ex-db-rdl', 'DB Romanian Deadlift', 'strength', 'hamstrings,glutes,lower_back', 'dumbbell', 'Dumbbells track down the legs. Hips move back, knees stay soft, spine stays long.', 'https://www.youtube.com/watch?v=JCXUYuzwNrM', strftime('%s','now')),
('ex-db-ohp', 'DB Overhead Press', 'strength', 'shoulders,triceps,core', 'dumbbell', 'Brace ribs down. Press dumbbells overhead without leaning back.', 'https://www.youtube.com/watch?v=qEwKCR5JCog', strftime('%s','now')),
('ex-lat-pulldown', 'Lat Pulldown', 'strength', 'back,biceps', 'machine,cable', 'Pull elbows down toward ribs. Chest tall, no swinging.', 'https://www.youtube.com/watch?v=CAwf7n6Luuc', strftime('%s','now')),
('ex-hamstring-curl', 'Hamstring Curl', 'strength', 'hamstrings', 'machine', 'Curl under control, pause, and return slowly without lifting the hips.', 'https://www.youtube.com/watch?v=1Tq3QdYUuHs', strftime('%s','now')),
('ex-push-up', 'Push-Up', 'strength', 'chest,shoulders,triceps,core', 'bodyweight', 'Straight line from head to heels. Lower with control, press the floor away.', 'https://www.youtube.com/watch?v=IODxDxX7oi4', strftime('%s','now')),
('ex-pike-push-up', 'Pike Push-Up', 'strength', 'shoulders,triceps,core', 'bodyweight', 'Hips high, head travels toward the floor between the hands. Press back up without collapsing the neck.', 'https://www.youtube.com/watch?v=x7_IW_Su2-4', strftime('%s','now')),
('ex-tempo-squat', 'Tempo Squat', 'strength', 'quads,glutes,core', 'bodyweight,band', 'Descend for three seconds, pause briefly, and stand with control.', 'https://www.youtube.com/watch?v=aclHkVaku9U', strftime('%s','now')),
('ex-reverse-lunge', 'Reverse Lunge', 'strength', 'quads,glutes,hamstrings', 'bodyweight,dumbbell,band', 'Step back, keep front foot planted, and stand through the front leg.', 'https://www.youtube.com/watch?v=QOVaHwm-Q6U', strftime('%s','now')),
('ex-single-leg-rdl', 'Single-Leg RDL', 'strength', 'hamstrings,glutes,balance', 'bodyweight,dumbbell', 'Hinge on one leg with hips square. Reach long, then stand by squeezing the glute.', 'https://www.youtube.com/watch?v=YMx4z2itkx8', strftime('%s','now')),
('ex-lateral-lunges', 'Lateral Lunges', 'mobility', 'adductors,glutes,quads', 'bodyweight', 'Step wide, sit into one hip, other leg stays straight. 8 each side. Frontal-plane prep for running and kicking.', 'https://www.youtube.com/watch?v=4NlJdSzHeUg', strftime('%s','now'));
