import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

// ─── Training structure ────────────────────────────────────────

export const trainingBlocks = sqliteTable('training_blocks', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  blockType: text('block_type').notNull().default('fighter'),
  totalWeeks: integer('total_weeks').notNull(),
  startedAt: integer('started_at'),
  endedAt: integer('ended_at'),
  status: text('status').notNull().default('active'),
  createdAt: integer('created_at').notNull(),
})

export const weekPlans = sqliteTable('week_plans', {
  id: text('id').primaryKey(),
  blockId: text('block_id').notNull().references(() => trainingBlocks.id),
  weekNumber: integer('week_number').notNull(),
  status: text('status').notNull().default('draft'),
  approvedAt: integer('approved_at'),
  autoGenerated: integer('auto_generated').notNull().default(0),
  notes: text('notes'),
  analysisJson: text('analysis_json'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_week_plans_block').on(t.blockId, t.weekNumber),
])

export const runningPlanWeeks = sqliteTable('running_plan_weeks', {
  id: text('id').primaryKey(),
  blockId: text('block_id').notNull().references(() => trainingBlocks.id),
  weekNumber: integer('week_number').notNull(),
  dayOfWeek: integer('day_of_week').notNull(),
  runType: text('run_type').notNull(),
  targetDesc: text('target_desc'),
  targetDurSec: integer('target_dur_sec'),
  targetDistKm: real('target_dist_km'),
}, (t) => [
  index('idx_rpw_block').on(t.blockId, t.weekNumber),
])

// ─── Sessions (hub table) ──────────────────────────────────────

export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey(),
  type: text('type').notNull(),
  weekPlanId: text('week_plan_id').references(() => weekPlans.id),
  scheduledDate: integer('scheduled_date'),
  timeSlot: text('time_slot'),
  status: text('status').notNull().default('planned'),
  startedAt: integer('started_at'),
  completedAt: integer('completed_at'),
  durationSec: integer('duration_sec'),
  rpe: integer('rpe'),
  difficulty: integer('difficulty'),
  blockWeek: integer('block_week'),
  blockType: text('block_type').notNull().default('fighter'),
  label: text('label'),
  notes: text('notes'),
  review: text('review'),
  reviewFlag: text('review_flag'),
  adjustmentId: text('adjustment_id'),
  skipReason: text('skip_reason'),
  skipReasonDetail: text('skip_reason_detail'),
  contextJson: text('context_json'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_sessions_date').on(t.scheduledDate),
  index('idx_sessions_week').on(t.weekPlanId),
  index('idx_sessions_type').on(t.type),
  index('idx_sessions_status').on(t.status, t.scheduledDate),
])

// ─── Strength sessions ─────────────────────────────────────────

export const strengthSessionExercises = sqliteTable('strength_session_exercises', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  exerciseId: text('exercise_id').notNull().references(() => exercises.id),
  orderIndex: integer('order_index').notNull(),
  section: text('section'),
  notes: text('notes'),
}, (t) => [
  index('idx_sse_session').on(t.sessionId),
])

export const strengthSets = sqliteTable('strength_sets', {
  id: text('id').primaryKey(),
  sessionExerciseId: text('session_exercise_id').notNull().references(() => strengthSessionExercises.id),
  setNumber: integer('set_number').notNull(),
  weightKg: real('weight_kg'),
  reps: integer('reps').notNull(),
  plannedWeightKg: real('planned_weight_kg'),
  plannedReps: integer('planned_reps'),
  inferredStatus: text('inferred_status'),
  loadFeedback: text('load_feedback'),
  bandColor: text('band_color'),
  isWarmup: integer('is_warmup').notNull().default(0),
  restSec: integer('rest_sec'),
  completedAt: integer('completed_at'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_sets_exercise').on(t.sessionExerciseId),
])

// ─── Bag work sessions ─────────────────────────────────────────

export const bagWorkRounds = sqliteTable('bag_work_rounds', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  roundNumber: integer('round_number').notNull(),
  durationSec: integer('duration_sec').notNull().default(180),
  restSec: integer('rest_sec').notNull().default(60),
  roundType: text('round_type').notNull().default('combo_practice'),
  coachRationale: text('coach_rationale').notNull().default(''),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_bwr_session').on(t.sessionId),
])

export const bagWorkRoundCombos = sqliteTable('bag_work_round_combos', {
  id: text('id').primaryKey(),
  roundId: text('round_id').notNull().references(() => bagWorkRounds.id),
  comboId: text('combo_id').notNull().references(() => combos.id),
  orderIndex: integer('order_index').notNull(),
}, (t) => [
  index('idx_bwrc_round').on(t.roundId),
])

// ─── Running sessions ──────────────────────────────────────────

export const runSessions = sqliteTable('run_sessions', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  planWeek: integer('plan_week'),
  runType: text('run_type'),
  distanceKm: real('distance_km'),
  durationSec: integer('duration_sec'),
  plannedDurationSec: integer('planned_duration_sec'),
  completionRatio: real('completion_ratio'),
  completionStatus: text('completion_status'),
  shortReason: text('short_reason'),
  paceSecKm: integer('pace_sec_km'),
  isIndoor: integer('is_indoor').notNull().default(0),
  onePaceArc: text('one_pace_arc'),
  onePaceEp: text('one_pace_ep'),
  avgHr: integer('avg_hr'),
  maxHr: integer('max_hr'),
  zoneSeconds: text('zone_seconds'),
  elevationGainM: integer('elevation_gain_m'),
  source: text('source').notNull().default('manual'),
  stravaActivityId: integer('strava_activity_id'),
  attachmentStatus: text('attachment_status'),
}, (t) => [
  uniqueIndex('idx_run_session').on(t.sessionId),
  uniqueIndex('idx_run_strava').on(t.stravaActivityId),
])

export const runSplits = sqliteTable('run_splits', {
  id: text('id').primaryKey(),
  runSessionId: text('run_session_id').notNull().references(() => runSessions.id),
  kmIndex: integer('km_index').notNull(),
  durationSec: integer('duration_sec').notNull(),
  avgHr: integer('avg_hr'),
  elevationGainM: integer('elevation_gain_m'),
}, (t) => [
  index('idx_run_splits_session').on(t.runSessionId),
])

// ─── Posture corrective sessions ───────────────────────────────

export const postureSessionExercises = sqliteTable('posture_session_exercises', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  exerciseId: text('exercise_id').notNull().references(() => exercises.id),
  orderIndex: integer('order_index').notNull(),
  holdSec: integer('hold_sec'),
  sets: integer('sets').default(1),
  completed: integer('completed').notNull().default(0),
}, (t) => [
  index('idx_pse_session').on(t.sessionId),
])

// ─── Skip rope sessions ────────────────────────────────────────

export const skipRopeSessions = sqliteTable('skip_rope_sessions', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  roundCount: integer('round_count').notNull(),
  roundDurSec: integer('round_dur_sec').notNull().default(180),
}, (t) => [
  uniqueIndex('idx_skip_session').on(t.sessionId),
])

// ─── Active recovery sessions ──────────────────────────────────

export const activeRecoverySessions = sqliteTable('active_recovery_sessions', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  hipMobility: integer('hip_mobility').notNull().default(0),
  foamRolling: integer('foam_rolling').notNull().default(0),
}, (t) => [
  uniqueIndex('idx_recovery_session').on(t.sessionId),
])

// ─── MT class logs ─────────────────────────────────────────────

export const mtClassLogs = sqliteTable('mt_class_logs', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  classType: text('class_type'),
  focusSkill: text('focus_skill'),
  weakness: text('weakness'),
  concept: text('concept'),
  actionItems: text('action_items'),
}, (t) => [
  uniqueIndex('idx_mt_session').on(t.sessionId),
])

// ─── Exercise library (seed data) ──────────────────────────────

export const exercises = sqliteTable('exercises', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  category: text('category').notNull(),
  muscleGroups: text('muscle_groups'),
  equipment: text('equipment'),
  formCues: text('form_cues'),
  formVideoUrl: text('form_video_url'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_exercises_category').on(t.category),
])

// ─── Combo library (seed data) ─────────────────────────────────

export const combos = sqliteTable('combos', {
  id: text('id').primaryKey(),
  text: text('text').notNull(),
  tier: text('tier').notNull(),
  level: text('level').notNull(),
  unlocked: integer('unlocked').notNull().default(0),
  masteryScore: integer('mastery_score').notNull().default(0),
  techniques: text('techniques').notNull().default(''),
  formTips: text('form_tips').default(''),
  isFavourite: integer('is_favourite').notNull().default(0),
  timesSharp: integer('times_sharp').notNull().default(0),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_combos_tier').on(t.tier, t.level),
])

export const comboPerformance = sqliteTable('combo_performance', {
  id: text('id').primaryKey(),
  comboId: text('combo_id').notNull().references(() => combos.id),
  sessionId: text('session_id').notNull().references(() => sessions.id),
  roundId: text('round_id').notNull().references(() => bagWorkRounds.id),
  rating: integer('rating').notNull().default(0),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_cp_combo').on(t.comboId),
  index('idx_cp_session').on(t.sessionId),
])

// ─── Wellness ──────────────────────────────────────────────────

export const dailyLogs = sqliteTable('daily_logs', {
  id: text('id').primaryKey(),
  logDate: integer('log_date').notNull().unique(),
  sleepHours: real('sleep_hours'),
  weedGrams: real('weed_grams'),
  alcoholScale: integer('alcohol_scale'),
  soreness: integer('soreness'),
  notes: text('notes'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_daily_log_date').on(t.logDate),
])

export const weeklyJournals = sqliteTable('weekly_journals', {
  id: text('id').primaryKey(),
  weekStart: integer('week_start').notNull().unique(),
  reflection: text('reflection'),
  prompt: text('prompt'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_journal_week').on(t.weekStart),
])

// ─── Journal entries ──────────────────────────────────────────

export const journalEntries = sqliteTable('journal_entries', {
  id: text('id').primaryKey(),
  date: integer('date').notNull(),
  type: text('type').notNull(), // 'daily' | 'weekly'
  content: text('content').notNull(),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_journal_date').on(t.date),
  index('idx_journal_type_date').on(t.type, t.date),
])

// ─── Training intelligence ────────────────────────────────────

export const weekAdjustments = sqliteTable('week_adjustments', {
  id: text('id').primaryKey(),
  weekPlanId: text('week_plan_id').notNull().references(() => weekPlans.id),
  adjustmentType: text('adjustment_type').notNull(), // 'skip_reschedule' | 'deficit_carryforward' | 'wellness_adapt' | 'pattern_adjust'
  sessionType: text('session_type').notNull(),
  action: text('action').notNull(), // 'add' | 'swap' | 'remove' | 'move_timeslot'
  reason: text('reason').notNull(),
  targetDay: integer('target_day'), // day of week (0-6)
  targetTimeSlot: text('target_time_slot'), // 'am' | 'pm'
  sourceData: text('source_data'), // JSON: wellness snapshot, skip context
  status: text('status').notNull().default('proposed'), // 'proposed' | 'accepted' | 'rejected'
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_wa_week').on(t.weekPlanId),
  index('idx_wa_status').on(t.status),
])

// ─── Config ────────────────────────────────────────────────────

export const settings = sqliteTable('settings', {
  id: text('id').primaryKey().default('default'),
  mtClassDays: text('mt_class_days'),
  amReminder: text('am_reminder'),
  pmLeadMin: integer('pm_lead_min'),
  pmSessionTime: text('pm_session_time'),
  onePaceArc: text('one_pace_arc'),
  onePaceEp: text('one_pace_ep'),
  lastDeploy: integer('last_deploy'),
  enabledTechniques: text('enabled_techniques').notNull().default('boxing,kicks,defensive'),
  amEnabled: integer('am_enabled').notNull().default(1),
  pmEnabled: integer('pm_enabled').notNull().default(1),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
})

export const trainingMaxes = sqliteTable('training_maxes', {
  id: text('id').primaryKey(),
  exerciseId: text('exercise_id').notNull().references(() => exercises.id),
  weightKg: real('weight_kg').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (t) => [
  uniqueIndex('idx_max_exercise').on(t.exerciseId),
])

// ─── AI coaching foundation ────────────────────────────────────

export const userProfile = sqliteTable('user_profile', {
  id: text('id').primaryKey().default('default'),
  goals: text('goals'),
  injuries: text('injuries'),
  postureIssues: text('posture_issues'),
  trainingHistory: text('training_history'),
  mtGymAccessDays: text('mt_gym_access_days'),
  mtCapPerWeek: integer('mt_cap_per_week'),
  weeklyDayTarget: integer('weekly_day_target'),
  constraints: text('constraints'),
  maxHr: integer('max_hr'),
  dob: text('dob'),
  onboardedAt: integer('onboarded_at'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
})

export const bodyMetrics = sqliteTable('body_metrics', {
  id: text('id').primaryKey(),
  loggedAt: integer('logged_at').notNull(),
  weightKg: real('weight_kg'),
  restingHr: integer('resting_hr'),
  bodyfatPct: real('bodyfat_pct'),
  notes: text('notes'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_body_metrics_logged').on(t.loggedAt),
])

// ─── Strava integration ───────────────────────────────────────

export const stravaTokens = sqliteTable('strava_tokens', {
  id: text('id').primaryKey().default('default'),
  athleteId: integer('athlete_id').notNull(),
  athleteName: text('athlete_name'),
  accessToken: text('access_token').notNull(),
  refreshToken: text('refresh_token').notNull(),
  expiresAt: integer('expires_at').notNull(),
  scope: text('scope').notNull(),
  connectedAt: integer('connected_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
})

export const appLogs = sqliteTable('app_logs', {
  id: text('id').primaryKey(),
  ts: integer('ts').notNull(),
  level: text('level').notNull(), // 'debug' | 'info' | 'warn' | 'error'
  category: text('category').notNull(), // 'api' | 'session' | 'nav' | 'error' | 'system'
  message: text('message').notNull(),
  userMessage: text('user_message'),
  contextJson: text('context_json'),
  screen: text('screen'),
  sessionId: text('session_id'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_app_logs_ts').on(t.ts),
  index('idx_app_logs_level_ts').on(t.level, t.ts),
  index('idx_app_logs_session').on(t.sessionId, t.ts),
])

export const coachingOutputs = sqliteTable('coaching_outputs', {
  id: text('id').primaryKey(),
  kind: text('kind').notNull(),
  model: text('model').notNull(),
  scopeWeekPlanId: text('scope_week_plan_id').references(() => weekPlans.id),
  scopeSessionId: text('scope_session_id').references(() => sessions.id),
  inputHash: text('input_hash'),
  outputJson: text('output_json').notNull(),
  tokensIn: integer('tokens_in'),
  tokensOut: integer('tokens_out'),
  cachedTokensIn: integer('cached_tokens_in'),
  createdAt: integer('created_at').notNull(),
}, (t) => [
  index('idx_coaching_kind_created').on(t.kind, t.createdAt),
  index('idx_coaching_week').on(t.scopeWeekPlanId),
  index('idx_coaching_session').on(t.scopeSessionId),
])
